// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_mef_header
int read_mef_header();
RcppExport SEXP _MEF_read_mef_header() {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  rcpp_result_gen = Rcpp::wrap(read_mef_header());
  return rcpp_result_gen;
  END_RCPP
}

// ToC
Rcpp::NumericMatrix ToC();
RcppExport SEXP _MEF_ToC() {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  rcpp_result_gen = Rcpp::wrap(ToC());
  return rcpp_result_gen;
  END_RCPP
}

// decomp_mef
std::vector<int> decomp_mef();
RcppExport SEXP _MEF_decomp_mef() {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  rcpp_result_gen = Rcpp::wrap(decomp_mef());
  return rcpp_result_gen;
  END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
  {"_MEF_read_mef_header", (DL_FUNC) &_MEF_read_mef_header, 0},
  {"_MEF_ToC", (DL_FUNC) &_MEF_read_mef_header, 0},
  {"_MEF_decomp_mef", (DL_FUNC) &_MEF_read_mef_header, 0},
  {NULL, NULL, 0}
};

RcppExport void R_init_MEF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
